seada/seadaAnalysis/seadaAnalysis/seadaAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('dashboard/', include('dashboard.urls')),
    path('twitter/', include('twitter.urls')),
    path('admin/', admin.site.urls),
]

seada/seadaAnalysis/seadaAnalysis/twitter/urls.py
from django.urls import path

from . import views

app_name = 'twitter'
urlpatterns = [
    path('', views.index, name='twitter'),
    path('adduser/', views.add_user, name='adduser'),
    path('userlist/', views.userlist, name='userlist'),
    path('user/<str:user_id>', views.user, name='user'),
]

seada/seadaAnalysis/seadaAnalysis/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="Javier Guzmán Porras"/>
    <meta name="theme-color" content="#563d7c">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <title>{% block title %} SEADA Analysis {% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>
        <!-- navbar -->
        {% include 'navbar.html' %}
        <!-- End of navbar -->

        {% block content %}{% endblock %}

        <!-- Footer -->
        {% include 'footer.html' %}
        <!-- End of Footer -->

</body>
</html>

seada/seadaAnalysis/seadaAnalysis/templates/base_2col.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row" >
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <!-- sidebar -->
                {% include 'sidebar.html' %}
                <!-- End of sidebar -->
        </nav>

        <main class="col-md-9 ml-sm-auto col-lg-10 px-4" role="main">
            {% block main-content %}{% endblock %}
        </main>
    </div>
</div>
{% endblock %}

seada/seadaAnalysis/seadaAnalysis/templates/footer.html
<br>
<br>
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright © SEADA 2020</span>
        </div>
    </div>
</footer>

seada/seadaAnalysis/seadaAnalysis/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}


    <div class="jumbotron">
        <h1 class="display-4"><img src="{% static 'png/seada_logo.png' %}" alt="" width="184" height="55" title="home"></h1>
        <p class="lead">Sistema de Extracción y Análisis de Datos de fuentes Abiertas</p>
        <hr class="my-4">
        <p>This is the analysis web application for SEADA project</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <h2>Dashboard</h2>
                <p>Dashboard with graphic about users, tweets, followers, <br>friends and favorites information.</p>
                <p><a class="btn btn-secondary" href="{% url 'dashboard' %}" role="button">view details >></a></p>
            </div>
            <div class="col">
                <h2>Twitter Analysis Application</h2>
                <p>Application web for all twitter information <br> about users and tweets.</p>
                <p><a class="btn btn-secondary" href="{% url 'twitter:twitter' %}" role="button">view details >></a></p>
            </div>
        </div>
    </div>
    <br>
{% endblock %}

seada/seadaAnalysis/seadaAnalysis/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand navbar-dark bg-dark topbar">
  <img src="{% static 'png/seada_logo.png' %}" alt="" width="184" height="55" title="home">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
<!--        <a class="nav-link" href="/dashboard">Dashboard <span class="sr-only">(current)</span></a>-->
      </li>
    </ul>
  </div>
</nav>

seada/seadaAnalysis/seadaAnalysis/templates/sidebar.html
{% load static %}

<div class="sidebar-sticky">
    <ul class="nav flex-column">
        Analysis Web Application
        <li class="nav-item"><hr></li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'index' %}">
                <img src="{% static 'svg/home.svg' %}" alt="" width="16" height="16" title="home">
                SEADA Home
            </a>
        </li>
        <li class="nav-item"><hr></li>
        <li class="nav-item">
            <a class="nav-link active" href="/dashboard/">
                <img src="{% static 'svg/dashboard.svg' %}" alt="" width="16" height="16" title="dashboard">
                Dashboard
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'userlist' %}">
                <img src="{% static 'svg/people.svg' %}" alt="" width="16" height="16" title="people">
                Compare Users
            </a>
        </li>
        <li class="nav-item"><hr></li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'twitter:twitter' %}">
                <img src="{% static 'svg/people.svg' %}" alt="" width="16" height="16" title="people">
                SEADA Twitter app home
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'twitter:userlist' %}">
                <img src="{% static 'svg/people.svg' %}" alt="" width="16" height="16" title="people">
                Twitter User List
            </a>
        </li>
    </ul>
</div>